export const BLOGPOST_LOADING = 'BLOGPOST_LOADING';
export const SET_BLOGPOST_NOT_LOADING = 'SET_BLOGPOST_NOT_LOADING';

export const GET_BLOGPOST_REQUEST = 'GET_BLOGPOST_REQUEST';
export const GET_BLOGPOST_SUCCESS = 'GET_BLOGPOST_SUCCESS';
export const GET_BLOGPOST_FAILURE = 'GET_BLOGPOST_FAILURE';

export const GET_BLOGPOSTS_REQUEST = 'GET_BLOGPOSTS_REQUEST';
export const GET_BLOGPOSTS_SUCCESS = 'GET_BLOGPOSTS_SUCCESS';
export const GET_BLOGPOSTS_FAILURE = 'GET_BLOGPOSTS_FAILURE';

export const GET_BLOGPOSTS = 'GET_BLOGPOSTS';
export const ADD_BLOGPOST_SUCCESS = 'ADD_BLOGPOST_SUCCESS';
export const UPDATE_BLOGPOST = 'UPDATE_BLOGPOST';
export const DELETE_BLOGPOST = 'DELETE_BLOGPOST';
export const SHUFFLE_BLOGPOSTS = 'SHUFFLE_BLOGPOSTS';
export const GET_DATES = 'GET_DATES';
