export const PROJECT_LOADING = "PROJECT_LOADING";
export const SET_PROJECT_NOT_LOADING = "SET_PROJECT_NOT_LOADING";
export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
